# Generated by Django 3.1 on 2020-08-30 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200830_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datecomp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 21, 30, 1, 316217)),
        ),
    ]
